apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trip-collector
    part: trip-collector-backend
  name: trip-collector-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trip-collector
      part: trip-collector-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trip-collector
        part: trip-collector-backend
    spec:
      containers:
        - image: registry.mk8s.lanodispenser.no/trip-collector-backend
          name: trip-collector-backend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trip-collector
    part: trip-collector-backend
  name: trip-collector-backend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    part: trip-collector-backend
