apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-collector-db
  labels:
    app: trip-collector
    part: trip-collector-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-collector
      part: trip-collector-db
  template:
    metadata:
      labels:
        app: trip-collector
        part: trip-collector-db
    spec:
      containers:
      - name: trip-collector-db
        image: hantonsen/trip-collector.db
        ports:
        - containerPort: 27018
---
apiVersion: v1
kind: Service
metadata:
  name: trip-collector-db
  labels:
    app: trip-collector
    part: trip-collector-db
spec:
  selector:
    part: trip-collector-db
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27018