name: Server CI/CD

on:
  push:
    branches: [ master ]
    paths:
    - "server/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.mk8s.lanodispenser.no
      APP: trip-collector-backend
    steps:
    - uses: actions/checkout@master
    - name: Set SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - working-directory: server
      run: |
        docker build . -t $REGISTRY/$APP:${{ steps.vars.outputs.sha_short }}
        docker push $REGISTRY/$APP:${{ steps.vars.outputs.sha_short }}
      
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Jtalk/k8s-deploy@v2
      with:
        manifests: |
          server/deployment.yaml
        images: |
          registry.mk8s.lanodispenser.no/trip-collector-backend:${{ steps.vars.outputs.sha_short }}