name: Server CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: registry.mk8s.lanodispenser.no:20443
      APP: trip-collector-backend

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: server
      run: lein deps
    - name: Run tests
      working-directory: server
      run: lein test
    - name: Build
      working-directory: server
      run: lein uberjar
    - name: Set SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build image
      working-directory: server
      run: docker build . -t $REGISTRY/$APP
    - name: Tag image
      working-directory: server
      run: docker tag $REGISTRY/$APP $REGISTRY/$APP:${{ steps.vars.outputs.sha_short }}
    - name: Push sha
      working-directory: server
      run: docker push $REGISTRY/$APP:${{ steps.vars.outputs.sha_short }}
    - name: Push latest
      working-directory: server
      run: docker push $REGISTRY/$APP:latest